fio = input("Введите ФИО исследователя: ")
data = input("Введите дату проведения исследования: ")
exp = input("Введите название эксперимента: ")
conclusion = input("Введите вывод вашего эксперимента: ")
conclusion_0 = conclusion.split()
min =("+" + "-" * 55 + "+")

with open("journal2.txt", "w", encoding="utf-8") as page:
    page.write(min)
    page.write(f"\n| Электронный лабораторный журнал\t\t\t|\n")
    page.write(min)
    page.write(f"\n| ФИО исследователя\t: {fio}\t\t|\n")
    page.write(f"| Дата\t\t\t: {data}\t\t\t|\n")
    page.write(f"| Эксперимент\t\t: {exp}\t|\n")
    page.write(min)
    page.write(f"\n| Вывод:\t\t\t\t\t\t|\n")
    page.write(f"| {conclusion_0[0:5]}|\n")
    page.write(f"| {conclusion_0[5:9]}|\n")
    page.write(f"| {conclusion_0[9:10]}\t\t\t\t\t\t|\n")
    page.write(min)
